version: "3.3"
services:
  master:
    image: eeacms/jenkins-master
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: eeacms/jenkins-slave
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 50M
        reservations:
          cpus: '0.0001'
          memory: 20M
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "admin"
      JENKINS_PASS: "1234"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker: